name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: Publishing
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 18
          packageManager: pnpm

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=$NPM_EMAIL
            name=$NPM_NAME
            registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_NAME: ${{ secrets.NPM_NAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          commit: ':package: RELEASE: new version'
          title: ':package: RELEASE: preparing next version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
